# The default target of this Makefile is...
all:: git-credential-osxkeychain

git-credential-osxkeychain:
	cd ../../..; make contrib/credential/osxkeychain/git-credential-osxkeychain

install:
	cd ../../..; make install-git-credential-osxkeychain

clean:
	cd ../../..; make clean-git-credential-osxkeychain

.PHONY: all git-credential-osxkeychain install clean
